erDiagram
CLIENT ||--o{ ORDER : ""
CLIENT ||--o{ RENTAL : ""
STAFF ||--o{ ORDER : ""
STAFF||--o{ RENTAL : ""
STAFF ||--o{ CLUB_MEETING : ""
ORDER ||--|{ ORDER_ITEM : ""
BOOK ||--o{ ORDER_ITEM : ""
BOOK ||--o{ CLUB_MEETING : ""

STAFF {
    int id PK
    string name
    string surname
    string job
}

CLIENT {
    int id PK
    string name
    string surname
    string phone
    string email
    int bonuses
}

BOOK {
    int id PK
    string author
    int year
    string genre
    decimal price
    int number_in_stock
}

ORDER {
    int id PK
    int client_id FK
    int staff_id FK
    date order_date 
    decimal price
    string status
}

RENTAL {
    int id PK
    int client_id FK 
    int staff_id FK 
    int book_id FK
    date rental_date
    date return_date
}

CLUB_MEETING {
    int id PK
    int book_id FK
    int staff_id FK
    date meeting_date
}

ORDER_ITEM {
    int id PK
    int order_id FK
    int book_id FK
    int game_id FK
    int quantity
    decimal unit_price
}
