erDiagram
CLIENT ||--o{ ORDER : ""
CLIENT ||--o{ RENTAL : ""
STAFF ||--o{ ORDER : ""
STAFF||--o{ RENTAL : ""
STAFF ||--o{ CLUB_MEETING : ""
CLIENT }o--o{ CLUB_MEETING: ""
BOOK |o--o{ CLUB_MEETING: ""
BOARD_GAME |o--o{ CLUB_MEETING: ""
ORDER ||--|{ ORDER_ITEM : ""
BOOK_COPY ||--o{ RENTAL : ""
BOOK ||--|{ BOOK_COPY: ""
PRODUCT ||--o|BOOK: ""
PRODUCT ||--o|BOARD_GAME: ""
PRODUCT |o--o{ORDER_ITEM: ""

STAFF {
    int id PK
    string name
    string surname
    string job
}

CLIENT {
    int id PK
    string name
    string surname
    string phone
    string email
    int bonuses
}

BOOK {
    int id PK
    int product_id FK
    string author
    string title
    int year
    string genre
}

BOARD_GAME {
    int id PK
    int product_id FK
    string name
    int age_restriction
    int number_of_players
}

PRODUCT {
    int id PK
    string name
    decimal price
    int number_in_stock
}


BOOK_COPY {
    int id PK
    int book_id FK
    string uniq_number
    string status
}

ORDER {
    int id PK
    int client_id FK
    int staff_id FK
    date order_date 
    decimal price
    string status
}

RENTAL {
    int id PK
    int client_id FK 
    int staff_id FK 
    int copy_id FK
    date rental_date
    date return_date
}

CLUB_MEETING {
    int id PK
    int book_id FK
    int game_id FK
    int staff_id FK
    date meeting_date
}

ORDER_ITEM {
    int id PK
    int order_id FK
    int product_id FK
    int quantity
    decimal unit_price
}

